chore: update ruby & bundler version for CI
* bundler 1.12.5 breaks with current version of dependencies
  (NoMethodError: undefined method `[]' for nil:NilClass)
* vagrant-2.2.17 requires ruby version ~> 2.5, < 2.8